language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew build; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then ./gradlew build; fi
  - if [ "$TRAVIS_BRANCH" = "branch1" ]; then ./gradlew build -x testBranch2; fi
  - if [ "$TRAVIS_BRANCH" = "branch2" ]; then ./gradlew build -x testBranch1; fi