language: java
sudo: false
install: true
jdk:
  - oraclejdk8
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then gradle build; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then gradle build; fi
  - if [ "$TRAVIS_BRANCH" = "branch2" ]; then gradle build -x testBranch1; 
  - if [ "$TRAVIS_BRANCH" = "branch1" ]; then gradle build -x testBranch2; fi